name: Build ADfilters

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        env:
         DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          sudo mkdir -p /rules
          sudo chown $USER:$GROUPS /rules

      - name: Working……
        working-directory: /rules
        run: |
          ln -sf /rules $GITHUB_WORKSPACE/private
          wget -t 3 -O filters_ https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt
          wget -t 3 -O badware_ https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt
          wget -t 3 -O privacy_ https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt
          wget -t 3 -O abuse_ https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt
          wget -t 3 -O unbreak_ https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt
          wget -t 3 -O f2020_ https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2020.txt
          wget -t 3 -O f2021_ https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2021.txt
          wget -t 3 -O f2022_ https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2022.txt
          wget -t 3 -O eprivacy_ https://easylist.to/easylist/easyprivacy.txt
          wget -t 3 -O echina_ https://raw.githubusercontent.com/easylist/easylistchina/master/easylistchina.txt
          wget -t 3 -O cjx_ https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
          wget -t 3 -O xinggsf_ https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt
          sed -i -e '/^!/d' -e '/^\s*$/d' *_
          cat *_ | sort | uniq > 0.txt
          echo -e "! Title: 广告过滤规则合集\n! Version: `date +"%y.%m.%d-%H"`\n! Description: uBlock + EasylistChina + EasyPrivacy + CJX'sAnnoyanceList + 乘风规则  [规则数:`cat 0.txt | wc -l`]" >> 0.txt

      - name: Download
        uses: actions/download-artifact@main
        with:
          name: rules
          path: /rules/0.txt
