name: Build ADfilters

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22-0,0-13/3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          sudo mkdir -p /rules
          sudo chown $USER:$GROUPS /rules

      - name: Build
        working-directory: /rules
        run: |
          echo "DIR=$PWD" >> $GITHUB_ENV
          wget -t 3 -O filters_ https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt
          wget -t 3 -O badware_ https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt
          wget -t 3 -O privacy_ https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/privacy.txt
          wget -t 3 -O abuse_ https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt
          wget -t 3 -O unbreak_ https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/unbreak.txt
          wget -t 3 -O f2020_ https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2020.txt
          wget -t 3 -O f2021_ https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2021.txt
          wget -t 3 -O f2022_ https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters-2022.txt
          wget -t 3 -O eprivacy_ https://easylist.to/easylist/easyprivacy.txt
          wget -t 3 -O echina_ https://raw.githubusercontent.com/easylist/easylistchina/master/easylistchina.txt
          wget -t 3 -O cjx_ https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
          wget -t 3 -O xinggsf_ https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt
          sed -i -e '/^!/d' -e '/^\s*$/d' *_
          cat *_ | sort | uniq > 0.txt
          echo -e "! Title: 广告过滤规则合集\n! Version: `date +"%y.%m.%d-%H"`\n! Description: uBlock + EasylistChina + EasyPrivacy + CJX'sAnnoyanceList + 乘风规则  [规则数:`cat 0.txt | wc -l`]" >> 0.txt
          echo -e "广告过滤规则合集\nVer: `date +"%y.%m.%d-%H"`\nuBlock + EasylistChina + EasyPrivacy + CJX'sAnnoyanceList + 乘风规则    [ 规则数:`cat 0.txt | wc -l` ]" > release.txt
          tar -zcvf rules.tar.gz 0.txt

      - name: Upload New Releases
        uses: softprops/action-gh-release@v0.1.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ADfilters
          body_path: ${{ env.DIR }}/release.txt
          files: ${{ env.DIR }}/rules.tar.gz

      - name: Delete older Releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 1
          delete_tags: true

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
